changed strtonum() to str2num()
Ryan Avella <rmavella@gmail.com> writes:

I received this error while compiling on FreeBSD

readshpfont.c:97:5: error: conflicting types for 'strtonum'
   97 | int strtonum(char *str) {
      |     ^~~~~~~~
In file included from readshpfont.c:6:
/usr/include/stdlib.h:318:2: note: previous declaration of 'strtonum' was here
  318 |  strtonum(const char *, long long, long long, const char **);
      |  ^~~~~~~~
gmake: *** [<builtin>: readshpfont.o] Error 1

Upon further investigation, it looks like all of the BSD's provide a
function strtonum in their stdlib.h.  It is not only a name conflict but
also a signature conflict.  FreeBSD's strtonum takes 4 arguments instead
of 1.

Changing strtonum to str2num fixes this.